### ISSUE TITLE
god status is crashing

### ISSUE THREAD

**Issue by jbmyid** [mojombo/god#249]
I am getting following error when using `god status`

version: Version 0.13.7

```

$ god status
Uncaught exception
comparison of String with Symbol failed
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/god-0.13.7/lib/god/cli/command.rb:111:in `sort'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/god-0.13.7/lib/god/cli/command.rb:111:in `status_command'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/god-0.13.7/lib/god/cli/command.rb:29:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/god-0.13.7/lib/god/cli/command.rb:10:in `initialize'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/god-0.13.7/bin/god:121:in `new'
/home/ubuntu/.rvm/gems/ruby-2.4.0/gems/god-0.13.7/bin/god:121:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.0/bin/god:22:in `load'
/home/ubuntu/.rvm/gems/ruby-2.4.0/bin/god:22:in `<main>'
/home/ubuntu/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jbmyid** [comment]
Fixed it 

I'd assign the group as a symbol and it was expecting string.
