### ISSUE TITLE
God appears to be leaving old god processes around indefinitely

### ISSUE THREAD

**Issue by ajsharp** [mojombo/god#51]
When god forks processes, whether to do monitoring or restart processes, it seems to leave a lot of these processes lying around. I seem to notice this happening when we after we do deploys, though not necessarily in a consistent manner. On deploys, we reload the god config (via `goad load`) and then we restart some processes. On our staging server, we only have a total of four processes being monitored, and we have 17 god processes running. Seems excessive. Also, on a recent deploy, I noticed this log output after reloading the god config.

We are using ruby 1.9.

```
I [2011-06-22 16:54:14]  INFO: api-unicorn-master-1 Reloaded config
I [2011-06-22 16:54:14]  INFO: resque-0 unwatched
F [2011-06-22 16:54:14] FATAL: Unhandled exception in driver loop - (NoMethodError): undefined method `handle_event' for nil:NilClass
/usr/local/rvm/gems/ruby-1.9.2-p180/gems/god-0.11.0/lib/god/driver.rb:151:in `block (2 levels) in initialize'
/usr/local/rvm/gems/ruby-1.9.2-p180/gems/god-0.11.0/lib/god/driver.rb:149:in `loop'
/usr/local/rvm/gems/ruby-1.9.2-p180/gems/god-0.11.0/lib/god/driver.rb:149:in `block in initialize'
I [2011-06-22 16:54:14]  INFO: resque-0 Reloaded config
I [2011-06-22 16:54:14]  INFO: resque-1 unwatched
F [2011-06-22 16:54:14] FATAL: Unhandled exception in driver loop - (NoMethodError): undefined method `handle_event' for nil:NilClass
/usr/local/rvm/gems/ruby-1.9.2-p180/gems/god-0.11.0/lib/god/driver.rb:151:in `block (2 levels) in initialize'
/usr/local/rvm/gems/ruby-1.9.2-p180/gems/god-0.11.0/lib/god/driver.rb:149:in `loop'
/usr/local/rvm/gems/ruby-1.9.2-p180/gems/god-0.11.0/lib/god/driver.rb:149:in `block in initialize'
I [2011-06-22 16:54:14]  INFO: resque-1 Reloaded config
I [2011-06-22 16:54:14]  INFO: resque-scheduler Loaded configI [2011-06-22 16:54:14]  INFO: resque-scheduler move 'unmonitored' to 'init'
D [2011-06-22 16:54:14] DEBUG: driver schedule #<God::Conditions::ProcessRunning:0x00000001cbae48> in 0 seconds
I [2011-06-22 16:54:14]  INFO: resque-scheduler moved 'unmonitored' to 'init'
I [2011-06-22 16:54:15]  INFO: resque-scheduler [trigger] process is running (ProcessRunning)
D [2011-06-22 16:54:15] DEBUG: resque-scheduler ProcessRunning [true] {true=>:up, false=>:start}
I [2011-06-22 16:54:15]  INFO: resque-scheduler move 'init' to 'up'
D [2011-06-22 16:54:15] DEBUG: driver schedule #<God::Conditions::MemoryUsage:0x00000001cbb9d8> in 0 seconds
D [2011-06-22 16:54:15] DEBUG: driver schedule #<God::Conditions::ProcessRunning:0x00000001cb9980> in 0 seconds
I [2011-06-22 16:54:15]  INFO: resque-scheduler moved 'init' to 'up'
I [2011-06-22 16:54:15]  INFO: resque-scheduler [ok] memory within bounds [73620kb] (MemoryUsage)
D [2011-06-22 16:54:15] DEBUG: resque-scheduler MemoryUsage [false] {true=>:restart}
D [2011-06-22 16:54:15] DEBUG: driver schedule #<God::Conditions::MemoryUsage:0x00000001cbb9d8> in 30 seconds
I [2011-06-22 16:54:15]  INFO: resque-scheduler [ok] process is running (ProcessRunning)D [2011-06-22 16:54:15] DEBUG: resque-scheduler ProcessRunning [false] {true=>:start}
D [2011-06-22 16:54:15] DEBUG: driver schedule #<God::Conditions::ProcessRunning:0x00000001cb9980> in 30 seconds
I [2011-06-22 16:54:15]  INFO: resque-1 move 'unmonitored' to 'restart'I [2011-06-22 16:54:15]  INFO: resque-scheduler move 'up' to 'restart'I [2011-06-22 16:54:15]  INFO: resque-0 move 'unmonitored' to 're
start'
I [2011-06-22 16:54:15]  INFO: resque-scheduler stop: kill -QUIT `cat /var/www/api/current/tmp/pids/resque-scheduler.pid`
I [2011-06-22 16:54:15]  INFO: resque-0 stop: kill -QUIT `cat /var/www/api/current/tmp/pids/resque-0.pid`
I [2011-06-22 16:54:15]  INFO: resque-1 stop: kill -QUIT `cat /var/www/api/current/tmp/pids/resque-1.pid`
```

**Comment by Aethelflaed** [comment]
:+1:
