### ISSUE TITLE
Unhandled exception (StandardError): No buffer space available

### ISSUE THREAD

**Issue by grempe** [mojombo/god#66]
I am seeing the following errors in /var/log/syslog continuously on some of my servers running in the EC2 cloud on Ubuntu 10.04.  

It seems to be raised from the following C code somewhere:

https://github.com/mojombo/god/blob/master/ext/god/netlink_handler.c#L26

```
Sep 19 20:44:40 localhost god[4886]: Unhandled exception (StandardError): No buffer space available#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/event_handler.rb:62:in `handle_events'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/event_handler.rb:62:in `start'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/event_handler.rb:60:in `loop'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/event_handler.rb:60:in `start'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/event_handler.rb:59:in `initialize'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/event_handler.rb:59:in `new'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/event_handler.rb:59:in `start'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/cli/run.rb:70:in `default_run'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/cli/run.rb:100:in `run_daemonized'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/cli/run.rb:91:in `fork'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/cli/run.rb:91:in `run_daemonized'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/cli/run.rb:21:in `dispatch'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/../lib/god/cli/run.rb:8:in `initialize'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/god:122:in `new'#012/usr/lib/ruby/gems/1.8/gems/god-0.11.0/bin/god:122#012/usr/bin/god:19:in `load'#012/usr/bin/god:19
```

```
$ god check
using event system: netlink
starting event handler
forking off new process
forked process with pid = 31687
killing process
[ok] process exit event received
```

```
$ uname -a
Linux HOSTNAME 2.6.35-22-virtual #35-Ubuntu SMP Sat Oct 16 23:57:40 UTC 2010 i686 GNU/Linux
```

```
$ ruby --version
ruby 1.8.7 (2010-06-23 patchlevel 299) [i686-linux]
```

```
$ god --version
Version 0.11.0
```

**Comment by ghost** [comment]
Still an issue...
